quarkus.application.name=data-index-ingestion-kafka-service

# http
quarkus.http.port=8080
quarkus.http.enable-compression=true

# health
quarkus.smallrye-health.root-path=/q/health

# jib
quarkus.container-image.build=true
quarkus.container-image.group=kubesmarts
quarkus.container-image.name=data-index-ingestion-kafka-service
quarkus.container-image.tag=999-SNAPSHOT

# kafka
%prod.kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS}

# mp messaging
mp.messaging.incoming.data-index-events.connector=smallrye-kafka
mp.messaging.incoming.data-index-events.topic=flow-lifecycle-out
mp.messaging.incoming.data-index-events.group.id=data-index-ingestion
mp.messaging.incoming.data-index-events.auto.offset.reset=earliest
mp.messaging.incoming.data-index-events.retry-attempts=2
mp.messaging.incoming.data-index-events.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.data-index-events.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.data-index-events.health-enabled=true
mp.messaging.incoming.data-index-events.health-readiness-enabled=true

mp.messaging.incoming.data-index-events.failure-strategy=dead-letter-queue
mp.messaging.incoming.data-index-events.dead-letter-queue.topic=data-index-events-dlq
mp.messaging.incoming.data-index-events.dead-letter-queue.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.incoming.data-index-events.dead-letter-queue.value.serializer=org.apache.kafka.common.serialization.StringSerializer

quarkus.native.resources.includes=task-instance-upsert.sql,task-placeholder-workflow-insert.sql,workflow-instance-upsert.sql